# Generated by Django 5.1.4 on 2024-12-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='cost_benefit_ratio',
        ),
        migrations.AddField(
            model_name='task',
            name='benefit',
            field=models.IntegerField(blank=True, help_text='Value gained (0-10)', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='cost',
            field=models.IntegerField(blank=True, help_text='Effort required (0-10)', null=True),
        ),
    ]
