# Generated by Django 5.1.4 on 2024-12-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_cost_benefit_ratio_task_benefit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.AddField(
            model_name='task',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='project_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='scope',
            field=models.TextField(blank=True, help_text='Project scope and objectives'),
        ),
        migrations.AddField(
            model_name='task',
            name='time_unit',
            field=models.CharField(blank=True, choices=[('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks')], default='hours', max_length=10, null=True),
        ),
    ]
